### ISSUE TITLE
value.toExponential is not a function

### ISSUE THREAD

**Issue by LvledPanic** [juviasuisei/tt2-optimizer#5]
My AD Sanity Check says NaN%, and in the javascript console I am seeing this error everytime I change anything: 

Uncaught TypeError: value.toExponential is not a function
    at displayTruncated (app.js:1286)
    at displayEffect (app.js:1294)
    at Object.<anonymous> (app.js:303)
    at Function.each (jquery-3.2.1.slim.min.js:2)
    at regenerateArtifacts (app.js:295)
    at determineArtifactWinner (app.js:1129)
    at calculate (app.js:1077)
    at adjustBoS (app.js:232)
    at adjustWeights (weights.js:107)
    at updateArtifact (app.js:385)

I can attach my export data if you need it.

**Comment by juviasuisei** [comment]
Please do. And try a hard refresh first. I’m not seeing that.

**Comment by LvledPanic** [comment]
huh, I had tried a hard refresh, but this time it fixed the NaN issue. However If I uncheck/check artifacts I still get that console error. I am using Chrome which could matter.

Export Data:
sc=titania=phom=online=0=0=0=0=0=1=1=e37=pct5=bos_1_120000000000|sov_1_29500000000000|coc_1_260000000000|hs_1_17000000000000|bop_1_390000000000|kb_1_17000000000000|zc_1_3000000000000|gfa_1_260000000000|coe_1_17000000000000|coe2_1_10000000000000|tbc_1_16900000000000|fots_1_646000000000|hsw_1_430000000000|dr_1_2150000000000|dh_1_50000000000000|ss_1_2040000000000|tr_1_60800000000000|stp_1_2270000000000|hb_1_48000000000000|tsos_1_11000000000000|fb_1_40000000000000|cota_1_48000000000000|ttt_1_5000000000000|hh_1_47000000000000|foe_1_178000|ie_1_900000000000|orc_1_18500000000000|hos2_1_702000000000|ao_1_480000000000|eop_1_60900000000000|af_1_100000000000|hos_1_900000000000|td_1_2150000000000|hs2_1_2150000000000|ob_1_450000000000|cotc_1_446000000000|ts2_1_480000000000|fg_1_360000000000|roc_1_666000000000|bod_1_2500000000000|hom_1_2100000000000|tp_1_2300000000000|mb_1_2500000000000|as_1_2500000000000|ig_1_29500000000000|tm_1_100000000000|rt_1_50000000000000|lp_1_43000000000000|bor_1_50000000000000|pof_1_50000000000000|eoe_1_60000000000000|hoti_1_40|pt_1_30|fs_1_30|rof_1_30|ga_1_30|a_1_30|sg_1_30|ip_1_20|gok_1_30|ts_1_40|os_1_30|tac_1_40|ho_1_40|ae_1_40|ms_1_40|mbos_1_40|eof_1_40|dc_1_50|is_1_50|aom_1_40|eotk_1_40|boh_1_40|ug_1_40|op_1_40|lfoa_1_40|lkm_1_40|sor_1_40|msw_1_50|tms_1_40|tmg_1_40|ttof_1_40|twd_1_50|as2_1_40|wod_1_60=kv_1_2|cho_1_3|pe_1_1|phom_1_15|cs_1_1|si_1_8|lbu_1_1|bf_1_6|fz_1_2|mc_1_2|sow_1_1|hm_1_7|aas_1_1|ti_1_4|sl_1_4|coo_1_5|aaw_1_3|as_1_10|lbr_1_2|mu_1_1|ar_1_1|pv_1_17|fc_1_10|ms_1_1|ed_1_7|mm_1_4|ls_1_2|ds_1_11|mt_1_11|an_1_11|sm_1_0|ab_1_1|tv_1_0|gs_1_0|sa_1_5

**Comment by LvledPanic** [comment]
Ah, I get the NaN% if an artifact is unchecked when the page loads.

**Comment by LvledPanic** [comment]
It also seems to be converting incorrectly. It's telling me to upgrade 3.00B when it's actually 30B

**Comment by juviasuisei** [comment]
Yeah, I had seen the 30 => 3.0. This was a result of me trying to clean-up how I was formatting numbers and I was a bit aggressive. That should be fixed now and while I was cleaning up that clean-up I think I also resolved your NaN% issue for AD sanity check. I can't make it happen anymore. Can you verify?

**Comment by LvledPanic** [comment]
Looks like it's fixed to me.
